language: python
dist: xenial
# require sudo to avoid Travis falling back to trusty; see
# https://github.com/travis-ci/travis-ci/issues/10110 and also
# https://github.com/travis-ci/travis-ci/issues/9069
sudo: required

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

# also test PyPy; do this on Trusty due to
# https://travis-ci.community/t/pypy-2-7-on-xenial/889
matrix:
  include:
    - python: "pypy"
      dist: trusty
      sudo: False
    - python: "pypy3"
      dist: trusty
      sudo: False

install:
  - git config --global user.email "bumpversion-test-git@travis.ci"
  - git config --global user.name "Testing Git on Travis CI"
  - git --version
  - git config --list
  - echo -e '[ui]\nusername = Testing Mercurial on Travis CI <bumpversion-test-hg@travis.ci>' > ~/.hgrc
  - hg --version
  - pip install tox-travis

script: tox
